# Generated by Django 4.1.2 on 2023-01-18 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_table',
            fields=[
                ('id', models.AutoField(default=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('contact_number', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.webp', null=True, upload_to='profiles')),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
