# Generated by Django 4.1.2 on 2023-01-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_register_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_table',
        ),
    ]
