# Generated by Django 4.1.2 on 2023-01-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_members_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='domain',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
