# Generated by Django 4.1.2 on 2023-01-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_task_task_alter_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskcomplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskcom', models.BooleanField(default=True, verbose_name='complete')),
            ],
        ),
    ]
