# Generated by Django 4.1.2 on 2023-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskcom',
            field=models.BooleanField(default=False, verbose_name='complete'),
        ),
    ]
