# Generated by Django 4.1.2 on 2023-01-20 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_task_taskcom'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
