# Generated by Django 4.1.2 on 2023-01-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_task_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion',
            field=models.DateField(),
        ),
    ]
