# Generated by Django 4.1.2 on 2023-01-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
