# Generated by Django 4.1.2 on 2023-01-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minutes', '0002_schedule_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
    ]
